on:
  push:
    branches:
      - master

jobs:
  main:
    strategy:
      matrix:
        os-version: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        node-version: ["lts/*"]
    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout [${{ matrix.os-version }}-${{ matrix.python-version }}-${{ matrix.node-version }}]
        uses: actions/checkout@v4
        with:
          # WARNING!! this is important
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
#      # https://github.com/actions/setup-python
#      - name: Setup Python toolchain for ${{ matrix.python-version }}
#        uses: actions/setup-python@v6
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - uses: actions/setup-node@v6
#        with:
#          node-version: ${{ matrix.node }}
#          cache: "npm"
#          cache-dependency-path: "**/package-lock.json"
#
#      # https://github.com/astral-sh/setup-uv
#      - name: Install uv
#        uses: astral-sh/setup-uv@v6
