on:
  push:
    branches:
      - master

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os-version: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        node-version: ["lts/*"]
    runs-on: ${{ matrix.os-version }}

    steps:
      # BOOKEEPING

      - name: Checkout [${{ matrix.os-version }}-${{ matrix.python-version }}-${{ matrix.node-version }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python toolchain ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup node toolchain ${{ matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      # INSTALL & RUN PART

      - name: Setup dependencies
        shell: bash
        run: |
          uv sync
          make frontend/node_modules

      - name: Test frontend
        shell: bash
        run: make test-js

      - name: Test backend
        shell: bash
        env:
          OUTDIR: build/qa-${{ matrix.python-version }}-${{ matrix.os-version }}-${{ matrix.node-version }}
        run: |
          mkdir -p $OUTDIR
          uv run pytest -vvs -l \
              --cov=lektor \
              --cov-report=html:$OUTDIR/coverage --cov-report=xml:$OUTDIR/coverage.xml \
              --junitxml=$OUTDIR/junit/junit.xml --html=$OUTDIR/junit/junit.html --self-contained-html \
            tests
